### ISSUE TITLE
Papers to read

### ISSUE THREAD

**Issue by Tan-JT** [TanJiaTing/AIP#4]
- [x] Misc -> pep 8, bigram, unigram,bm25, dense passage retriever
- [x] Papers -> ParlAI, drQA, unifiedQA

**Comment by DerekChia** [comment]
https://missing.csail.mit.edu/

This is a good resource to cover things that school normally don't teach.. Git.. etc.

**Comment by Tan-JT** [comment]
Ooh I'll go check it out, thanks for sharing
